version: '3.9'

services:

    app:
        build: .
        command: uvicorn main:app --host 0.0.0.0 --workers 4
        volumes:
            - .:/code
        # Running on 4 PORTS
        #ports:
            #- 80:8000
            #- 8000:8000
            #- 8001:8000

        #ports:
            # For nginx only port -80:80
            #- 8000:80

    nginx:
        build: ./nginx

        ports:
            - 80:80
            - 8000:8000
            - 8001:8001
            
        depends_on:
            - app

    